language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  # - jruby-19mode # JRuby in 1.9 mode
  # - rbx-19mode
# uncomment this line if your project needs to run something other than `rake`:
before_install: gem install rake
gemfile: .travis/gemfiles/Gemfile.empty
script: rake test:integration
